### ISSUE TITLE
关于memobird的项目

### ISSUE THREAD

**Issue by miedar** [atans/memobird#1]
求教，我用composer把您的memobird项目安装到机器上，但是运行test的时候总是提示Fatal error: Class 'Atans\Content\PrintContent' not found怎么回事呢。。。php零基础的我表示不懂啊。。请指点如何使用。。

**Comment by atans** [comment]
php 开头要加上 require "vendor/autoload.php";

**Comment by DrayChou** [comment]
加了还是不行，是不是依赖关系有问题？

**Comment by DrayChou** [comment]
路径问题，应该是：
use Atans\Memobird\Content\PrintContent;
