### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by mungle** [atans/memobird#2]
Hi...! Where can I findit? Thank you!

**Comment by mfyz** [comment]
same here, there is no documentation or information on the web on how to obtain the api key.

**Comment by swbuehler** [comment]
Neither would this work with the North American version of the device. Knectek Labs is on a separate API and they have not yet opened it up.

**Comment by drboudjelida** [comment]
To get the api access, submit a request here
https://open.memobird.cn/
